/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32CubeIDE Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Standard library includes for system calls */
#include <sys/stat.h>    /* For file status and mode definitions */
#include <stdlib.h>      /* For general utilities */
#include <errno.h>       /* For error handling */
#include <stdio.h>       /* For standard I/O operations */
#include <signal.h>      /* For signal handling */
#include <time.h>        /* For time operations */
#include <sys/time.h>    /* For time-related system calls */
#include <sys/times.h>   /* For process times */

/* External I/O function declarations with weak attribute for possible override */
extern int __io_putchar(int ch) __attribute__((weak));  /* Character output function */
extern int __io_getchar(void) __attribute__((weak));    /* Character input function */

/* Environment variables setup */
char *__env[1] = { 0 };          /* Empty environment array */
char **environ = __env;          /* Global environment pointer */

/* System call implementations */

/**
 * @brief Initialize monitor handles for debugging
 * @note Empty implementation as this is a minimal system
 */
void initialise_monitor_handles()
{
}

/**
 * @brief Get process ID
 * @return Always returns 1 as this is a single-process system
 */
int _getpid(void)
{
  return 1;  // Return 1 for single-process system
}

/**
 * @brief Send signal to process
 * @param pid Process ID (unused)
 * @param sig Signal number (unused)
 * @return -1 with EINVAL error as signals are not supported
 */
int _kill(int pid, int sig)
{
  (void)pid;  // Unused parameter
  (void)sig;  // Unused parameter
  errno = EINVAL;  // Set error to invalid argument
  return -1;  // Return error
}

/**
 * @brief Terminate process
 * @param status Exit status
 * @note Enters infinite loop after termination
 */
void _exit (int status)
{
  _kill(status, -1);  // Call kill with status
  while (1) {}    /* Make sure we hang here */  // Infinite loop
}

/**
 * @brief Read from file
 * @param file File descriptor (unused)
 * @param ptr Buffer to store read data
 * @param len Number of bytes to read
 * @return Number of bytes read
 */
__attribute__((weak)) int _read(int file, char *ptr, int len)
{
  (void)file;  // Unused parameter
  int DataIdx;  // Loop counter

  for (DataIdx = 0; DataIdx < len; DataIdx++)  // Loop through requested length
  {
    *ptr++ = __io_getchar();  // Read character and store in buffer
  }

  return len;  // Return number of bytes read
}

/**
 * @brief Write to file
 * @param file File descriptor (unused)
 * @param ptr Buffer containing data to write
 * @param len Number of bytes to write
 * @return Number of bytes written
 */
__attribute__((weak)) int _write(int file, char *ptr, int len)
{
  (void)file;  // Unused parameter
  int DataIdx;  // Loop counter

  for (DataIdx = 0; DataIdx < len; DataIdx++)  // Loop through requested length
  {
    __io_putchar(*ptr++);  // Write character from buffer
  }
  return len;  // Return number of bytes written
}

/**
 * @brief Close file
 * @param file File descriptor (unused)
 * @return -1 as file operations are not supported
 */
int _close(int file)  // Function to close file
{
  (void)file;  // Unused parameter
  return -1;  // Return error
}

/**
 * @brief Get file status
 * @param file File descriptor (unused)
 * @param st Pointer to stat structure
 * @return 0 on success
 */
int _fstat(int file, struct stat *st)  // Function to get file status
{
  (void)file;  // Unused parameter
  st->st_mode = S_IFCHR;  /* Treat as character device */ 
  return 0;  // Return success
}

/**
 * @brief Check if file is a terminal
 * @param file File descriptor (unused)
 * @return 1 as all files are treated as terminals
 */
int _isatty(int file)  // Function to check if file is terminal
{
  (void)file;  // Unused parameter
  return 1;  // Return true
}

/**
 * @brief Set file position
 * @param file File descriptor (unused)
 * @param ptr Position (unused)
 * @param dir Direction (unused)
 * @return 0 as file operations are not supported
 */
int _lseek(int file, int ptr, int dir)  // Function to set file position
{
  (void)file;  // Unused parameter
  (void)ptr;   // Unused parameter
  (void)dir;   // Unused parameter
  return 0;    // Return success
}

/**
 * @brief Open file
 * @param path File path (unused)
 * @param flags Open flags (unused)
 * @return -1 as file operations are not supported
 */
int _open(char *path, int flags, ...)  // Function to open file
{
  (void)path;   // Unused parameter
  (void)flags;  // Unused parameter
  /* Pretend like we always fail */  // Comment about failure
  return -1;    // Return error
}

/**
 * @brief Wait for child process
 * @param status Pointer to store exit status (unused)
 * @return -1 with ECHILD error as process operations are not supported
 */
int _wait(int *status)  // Function to wait for child process
{
  (void)status;  // Unused parameter
  errno = ECHILD;  // Set error to no child process
  return -1;  // Return error
}

/**
 * @brief Delete file
 * @param name File name (unused)
 * @return -1 with ENOENT error as file operations are not supported
 */
int _unlink(char *name)  // Function to delete file
{
  (void)name;  // Unused parameter
  errno = ENOENT;  // Set error to no such file
  return -1;  // Return error
}

/**
 * @brief Get process times
 * @param buf Pointer to times structure (unused)
 * @return -1 as timing operations are not supported
 */
int _times(struct tms *buf)  // Function to get process times
{
  (void)buf;  // Unused parameter
  return -1;  // Return error
}

/**
 * @brief Get file status
 * @param file File name (unused)
 * @param st Pointer to stat structure
 * @return 0 on success
 */
int _stat(char *file, struct stat *st)  // Function to get file status
{
  (void)file;  // Unused parameter
  st->st_mode = S_IFCHR;  /* Treat as character device */  // Set mode to character device
  return 0;  // Return success
}

/**
 * @brief Create hard link
 * @param old Old path (unused)
 * @param new New path (unused)
 * @return -1 with EMLINK error as file operations are not supported
 */
int _link(char *old, char *new)  // Function to create hard link
{
  (void)old;  // Unused parameter
  (void)new;  // Unused parameter
  errno = EMLINK;  // Set error to too many links
  return -1;  // Return error
}

/**
 * @brief Create new process
 * @return -1 with EAGAIN error as process operations are not supported
 */
int _fork(void)
{
  errno = EAGAIN;
  return -1;
}

/**
 * @brief Execute program
 * @param name Program name (unused)
 * @param argv Argument vector (unused)
 * @param env Environment variables (unused)
 * @return -1 with ENOMEM error as process operations are not supported
 */
int _execve(char *name, char **argv, char **env)
{
  (void)name;
  (void)argv;
  (void)env;
  errno = ENOMEM;
  return -1;
}
